[package]
name = "oxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
bitflags = "1.3.2"
glfw = "0.43.0"
log4rs = "1.0.0"
imgui = "0.7.0"
gl = "0.14.0"

